#Arquivo streamlit
openai_apikey = "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"
assistant_id = "asst_UHKpTmbExp7nfEDjVFZnMkTr"
